import { NextResponse } from 'next/server';
import { createProposedChangeSet } from '@archon/db';
import { getDatabase } from '../../../../../../lib/db';

type StructuredOperation={type?:string;targetId?:string;payload?:Record<string,unknown>};
type NormalizedOperation={type:string;targetId:string;payload:Record<string,unknown>};
type EditCommand={targetArchonId?:string;command?:string;operation?:StructuredOperation;operations?:StructuredOperation[];intentSummary?:string};
const DISTANCE=/(-?\d+(?:[.,]\d+)?)\s*(mm|cm|m)\b/;
const MAX_DIMENSION_MM=50000; const MAX_MOVE_MM=10000; const MAX_OPERATIONS=12;
function toMm(match:RegExpMatchArray){const raw=Number(match[1].replace(',','.'));const unit=match[2];const mm=unit==='m'?raw*1000:unit==='cm'?raw*10:raw;if(!Number.isFinite(mm)||mm<=0||mm>MAX_DIMENSION_MM)throw new Error('INVALID_DIMENSION');return mm}
function normalizeCommand(targetArchonId:string,command:string):NormalizedOperation{
 const normalized=command.trim().toLowerCase(); const amountMatch=normalized.match(DISTANCE); if(!amountMatch)throw new Error('COMMAND_REQUIRES_DISTANCE'); const amountMm=toMm(amountMatch);
 const dimensionIntent=/\b(lebar|width|lebarkan|sempitkan|tinggi|height|panjang|length|depth|kedalaman)\b/.test(normalized);
 if(dimensionIntent){let key:'widthMm'|'heightMm'|'depthMm'='widthMm';if(/\b(tinggi|height)\b/.test(normalized))key='heightMm';else if(/\b(panjang|length|depth|kedalaman)\b/.test(normalized))key='depthMm';return {type:'UPDATE',targetId:targetArchonId,payload:{[key]:amountMm}}}
 let axis:'X'|'Y'|'Z'='X';let sign=1;if(/\b(kiri|left)\b/.test(normalized)){axis='X';sign=-1}else if(/\b(kanan|right)\b/.test(normalized)){axis='X';sign=1}else if(/\b(atas|up)\b/.test(normalized)){axis='Y';sign=1}else if(/\b(bawah|down)\b/.test(normalized)){axis='Y';sign=-1}else if(/\b(depan|forward|north)\b/.test(normalized)){axis='Z';sign=-1}else if(/\b(belakang|back|south)\b/.test(normalized)){axis='Z';sign=1}else throw new Error('COMMAND_REQUIRES_DIRECTION_OR_DIMENSION');
 if(amountMm>MAX_MOVE_MM)throw new Error('MOVE_EXCEEDS_LIMIT'); const delta=amountMm*sign;return {type:'MOVE',targetId:targetArchonId,payload:axis==='X'?{deltaXmm:delta}:axis==='Y'?{deltaYmm:delta}:{deltaZmm:delta}};
}
function finite(value:unknown):value is number{return typeof value==='number'&&Number.isFinite(value)}
function normalizeStructured(operation:StructuredOperation,targetArchonId?:string):NormalizedOperation{const rawType=operation.type;if(typeof rawType!=='string')throw new Error('OPERATION_TYPE_REQUIRED');const type=rawType.trim().toUpperCase();const rawTarget=operation.targetId??targetArchonId;if(typeof rawTarget!=='string'||!rawTarget.trim())throw new Error('TARGET_REQUIRED');const targetId=rawTarget.trim();const payload=operation.payload??{};if(type==='MOVE'){const allowed=['deltaXmm','deltaYmm','deltaZmm'];const clean:Record<string,number>={};for(const key of allowed){const value=payload[key];if(value!==undefined){if(!finite(value)||Math.abs(value)>MAX_MOVE_MM)throw new Error('INVALID_MOVE_PAYLOAD');clean[key]=Math.round(value)}}if(!Object.keys(clean).length||Object.values(clean).every(value=>value===0))throw new Error('INVALID_MOVE_PAYLOAD');return {type:'MOVE',targetId,payload:clean}}
 if(type==='UPDATE'){const allowed=['widthMm','heightMm','depthMm'];const clean:Record<string,number>={};for(const key of allowed){const value=payload[key];if(value!==undefined){if(!finite(value)||value<=0||value>MAX_DIMENSION_MM)throw new Error('INVALID_DIMENSION');clean[key]=Math.round(value)}}if(!Object.keys(clean).length)throw new Error('INVALID_DIMENSION');return {type:'UPDATE',targetId,payload:clean}}throw new Error(`UNSUPPORTED_OPERATION:${type||'UNKNOWN'}`)}
function normalizeBatch(operations:StructuredOperation[],fallbackTarget?:string){if(!operations.length)throw new Error('NO_OPERATIONS');if(operations.length>MAX_OPERATIONS)throw new Error('TOO_MANY_OPERATIONS');return operations.map(operation=>normalizeStructured(operation,fallbackTarget))}
export async function POST(request:Request,context:{params:Promise<{projectId:string}>}){try{const {projectId}=await context.params;const body=await request.json() as EditCommand;const targetArchonId=body.targetArchonId?.trim();let operations:NormalizedOperation[];let intentSummary:string;if(body.operations){operations=normalizeBatch(body.operations,targetArchonId);intentSummary=body.intentSummary?.trim()||`Structured multi-operation proposal (${operations.length} operations)`}else if(body.operation){const operation=normalizeStructured(body.operation,targetArchonId);operations=[operation];intentSummary=body.intentSummary?.trim()||`Structured ${operation.type} proposal for ${operation.targetId}`}else{const command=body.command?.trim();if(!targetArchonId||!command)return NextResponse.json({error:'TARGET_AND_COMMAND_REQUIRED'},{status:400});operations=[normalizeCommand(targetArchonId,command)];intentSummary=command}const changeSet=await createProposedChangeSet(getDatabase(),{projectId,intentSummary,operations,createdBy:'ARCHON Assistant'});return NextResponse.json({ok:true,changeSet,normalizedOperations:operations},{status:201})}catch(error){const message=error instanceof Error?error.message:'UNKNOWN_ERROR';const conflict=message==='ACTIVE_CHANGESET_EXISTS';const badRequest=['TARGET_AND_COMMAND_REQUIRED','TARGET_REQUIRED','OPERATION_TYPE_REQUIRED','COMMAND_REQUIRES_DISTANCE','COMMAND_REQUIRES_DIRECTION_OR_DIMENSION','INVALID_DIMENSION','MOVE_EXCEEDS_LIMIT','NO_OPERATIONS','TOO_MANY_OPERATIONS','INVALID_MOVE_PAYLOAD'].includes(message)||message.startsWith('CANONICAL_TARGET_NOT_FOUND')||message.startsWith('UNSUPPORTED_OPERATION');const status=message==='DATABASE_URL_NOT_CONFIGURED'?503:message==='PROJECT_NOT_FOUND'?404:conflict?409:badRequest?400:500;return NextResponse.json({error:message},{status})}}
