'use client';
import { useRef,useState } from 'react';
import { Canvas, type ThreeEvent } from '@react-three/fiber';
import { Grid, OrbitControls,TransformControls } from '@react-three/drei';
import type { Group } from 'three';
import type { ChangeOperation } from './changeset-bar';
export type CanonicalObject={id:string;archonId:string;projectId:string;objectType:string;parameters:Record<string,unknown>|null;relationships:Record<string,unknown>|null;revision:number;provenance:Record<string,unknown>|null};
const MM_TO_M=.001;
function tuple(value:unknown):[number,number,number]|null{return Array.isArray(value)&&value.length===3&&value.every(v=>typeof v==='number')?value as [number,number,number]:null}
function finite(value:unknown){return typeof value==='number'&&Number.isFinite(value)&&value>0}
function applyOperation(position:[number,number,number],size:[number,number,number],operation:ChangeOperation){if(operation.type==='MOVE'){position[0]+=typeof operation.payload.deltaXmm==='number'?operation.payload.deltaXmm:0;position[1]+=typeof operation.payload.deltaYmm==='number'?operation.payload.deltaYmm:0;position[2]+=typeof operation.payload.deltaZmm==='number'?operation.payload.deltaZmm:0}else if(operation.type==='UPDATE'){if(finite(operation.payload.widthMm))size[0]=operation.payload.widthMm as number;if(finite(operation.payload.heightMm))size[1]=operation.payload.heightMm as number;if(finite(operation.payload.depthMm))size[2]=operation.payload.depthMm as number}}
function previewGeometry(item:CanonicalObject,operations:ChangeOperation[]=[]){const basePosition=tuple(item.parameters?.positionMm);const baseSize=tuple(item.parameters?.sizeMm);if(!basePosition||!baseSize)return null;const position:[number,number,number]=[...basePosition];const size:[number,number,number]=[...baseSize];for(const operation of operations){if(operation.targetId===item.archonId)applyOperation(position,size,operation)}return {position,size}}
function ObjectMesh({item,selected,onSelect}:{item:CanonicalObject;selected:boolean;onSelect:(item:CanonicalObject)=>void}){const geometry=previewGeometry(item);if(!geometry)return null;const position=geometry.position.map(v=>v*MM_TO_M) as [number,number,number];const size=geometry.size.map(v=>v*MM_TO_M) as [number,number,number];const click=(e:ThreeEvent<MouseEvent>)=>{e.stopPropagation();onSelect(item)};return <mesh position={position} userData={{archonId:item.archonId,revision:item.revision}} castShadow receiveShadow onClick={click}><boxGeometry args={size}/><meshStandardMaterial roughness={.72} metalness={.02} emissive={selected?'#6d8f21':'#000000'} emissiveIntensity={selected?.42:0}/></mesh>}
function PreviewMesh({item,operations}:{item:CanonicalObject;operations:ChangeOperation[]}){const geometry=previewGeometry(item,operations);if(!geometry)return null;const position=geometry.position.map(v=>v*MM_TO_M) as [number,number,number];const size=geometry.size.map(v=>v*MM_TO_M) as [number,number,number];return <mesh position={position} renderOrder={20}><boxGeometry args={size}/><meshStandardMaterial transparent opacity={.34} roughness={.35} metalness={.05} depthWrite={false} emissive="#9fe870" emissiveIntensity={.28}/></mesh>}
function GovernedGizmo({item,onMove,onDragging}:{item:CanonicalObject;onMove:(delta:[number,number,number])=>void;onDragging:(v:boolean)=>void}){const geometry=previewGeometry(item);const ref=useRef<Group>(null);if(!geometry)return null;const position=geometry.position.map(v=>v*MM_TO_M) as [number,number,number];const size=geometry.size.map(v=>v*MM_TO_M) as [number,number,number];const finish=()=>{const g=ref.current;if(!g)return;const delta:[number,number,number]=[Math.round((g.position.x-position[0])/MM_TO_M),Math.round((g.position.y-position[1])/MM_TO_M),Math.round((g.position.z-position[2])/MM_TO_M)];onDragging(false);if(delta.some(v=>Math.abs(v)>=1))onMove(delta)};return <TransformControls mode="translate" translationSnap={.01} onMouseDown={()=>onDragging(true)} onMouseUp={finish}><group ref={ref} position={position}><mesh><boxGeometry args={size}/><meshStandardMaterial transparent opacity={.12} depthWrite={false} emissive="#9fe870" emissiveIntensity={.5}/></mesh></group></TransformControls>}
export function Canonical3DViewport({version,objects,selectedId,onSelect,previewOperations=[],onProposeMove}:{version:number;objects:CanonicalObject[];selectedId?:string|null;onSelect:(item:CanonicalObject|null)=>void;previewOperations?:ChangeOperation[];onProposeMove?:(delta:[number,number,number])=>void}){const [dragging,setDragging]=useState(false);const previewTargetIds=[...new Set(previewOperations.map(operation=>operation.targetId))];const previewTargets=objects.filter(item=>previewTargetIds.includes(item.archonId));const selected=selectedId?objects.find(item=>item.archonId===selectedId):null;const moveCount=previewOperations.filter(operation=>operation.type==='MOVE').length;const updateCount=previewOperations.filter(operation=>operation.type==='UPDATE').length;const gizmoEnabled=Boolean(selected&&onProposeMove&&!previewOperations.length);return <div className="canonical-3d-shell"><div className="canonical-3d-status"><span>{previewOperations.length?'SANDBOX PREVIEW · APPROVED STATE LOCKED':'CANONICAL BUILDING GRAPH · LIVE DB'}</span><b>Approved Version {version||'—'}</b><small>{previewOperations.length?`${previewOperations.length} governed operations · ${previewTargetIds.length} affected objects · ${moveCount} move · ${updateCount} resize/update`:gizmoEnabled?'Drag XYZ gizmo · release creates governed MOVE proposal':'Units: mm · click object to inspect'}</small></div><Canvas shadows camera={{position:[22,18,24],fov:42}} onPointerMissed={()=>{if(!dragging)onSelect(null)}}><ambientLight intensity={1.2}/><directionalLight position={[12,22,8]} intensity={2.2} castShadow/><Grid args={[60,60]} cellSize={1} sectionSize={5} fadeDistance={50}/>{objects.map(item=><ObjectMesh key={item.id} item={item} selected={item.archonId===selectedId} onSelect={onSelect}/>) }{previewTargets.map(item=><PreviewMesh key={`preview-${item.id}`} item={item} operations={previewOperations.filter(operation=>operation.targetId===item.archonId)}/>)}{gizmoEnabled&&selected&&<GovernedGizmo item={selected} onDragging={setDragging} onMove={delta=>onProposeMove?.(delta)}/>}<OrbitControls makeDefault enabled={!dragging} target={[0,1,0]} minDistance={8} maxDistance={55}/></Canvas><div className="canonical-3d-legend"><strong>ARCHON Building Graph</strong><span>{objects.length} DB canonical objects</span><span>{previewOperations.length?`${previewTargetIds.length} ghost objects · all operations proposed only`:gizmoEnabled?'XYZ Gizmo · 10 mm snap · proposal on release':'Orbit · Pan · Zoom · Select'}</span></div></div>}
