import test from 'node:test';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {createPinnedSandboxReview} from './sandbox-review.mjs';import {sealValidatorReceipt} from './sandbox-validator-receipt.mjs';import {finalizeGovernedSandboxValidator} from './sandbox-validator-finalization.mjs';
const hash=v=>createHash('sha256').update(v).digest('hex'),namespace='owner',runId='archon-layout-smoke-20260912-v1',secret='a'.repeat(64);
const env={ARCHON_SANDBOX_VALIDATOR_FINALIZATION_ENABLED:'true',ARCHON_SANDBOX_VALIDATOR_RECEIPT_KEY:secret,APS_ACTIVITY_ID:namespace+'.ArchonGenerateLayout+v0_1',APS_APPBUNDLE_ID:namespace+'.ArchonLayoutBundle+v0_1',APS_AUTOCAD_ENGINE:'Autodesk.AutoCAD+25_1'},review=createPinnedSandboxReview(env),workitemId='validator-1',dwgSha256='b'.repeat(64),reportSha256='c'.repeat(64);
function artifactRow(){const evidence={schemaVersion:1,runId,manifestSha256:review.manifestSha256,workitemId:'generator-1',stage:'ARTIFACTS_VALIDATED',dwgSha256,reportSha256,nativeDwgReopenVerified:false,reconciliation:'PROPOSE_CHANGESET_ONLY',approvalGranted:false,checklist:[]};return {evidence_sha256:hash(JSON.stringify(evidence)),run_id:runId,manifest_sha256:review.manifestSha256,workitem_id:evidence.workitemId,stage:'ARTIFACTS_VALIDATED',dwg_sha256:dwgSha256,report_sha256:reportSha256,evidence,approval_granted:false};}
const reopenReport=Buffer.from(JSON.stringify({schemaVersion:1,entityCount:7,sourceVersionId:'test-version',nativeDwgReopenVerified:true,reconciliation:'PROPOSE_CHANGESET_ONLY',governanceAuthority:'NONE',approvalGranted:false,checklist:[{category:'native DWG reopen',status:'PASS'}]}));
function harness(state='APS_WORKITEM_SUCCEEDED'){const calls=[],row=artifactRow(),sealed=sealValidatorReceipt({receipt:{schemaVersion:1,runId,manifestSha256:review.manifestSha256,artifactEvidenceSha256:row.evidence_sha256,bucketKey:'archon_sandbox_'+'d'.repeat(24),reportKey:runId+'/archon-reopen-report.json',uploadKey:'private-upload',expiresAt:new Date(5000).toISOString()},secret,now:()=>1000});const receiptRow={run_id:runId,manifest_sha256:review.manifestSha256,artifact_evidence_sha256:row.evidence_sha256,ciphertext:sealed.ciphertext,iv:sealed.iv,auth_tag:sealed.authTag,expires_at:sealed.expiresAt};const reviewStore={lookup:async()=>{calls.push('evidenceLookup');return row;},store:async record=>{calls.push('nativeEvidence');assert.equal(record.stage,'NATIVE_REOPEN_VERIFIED');}};const validatorLedger={lookup:async()=>{calls.push('validatorLookup');return {run_id:runId,manifest_sha256:review.manifestSha256,artifact_evidence_sha256:row.evidence_sha256,state:'SUBMITTED',validator_workitem_id:workitemId};}};const validatorReceiptStore={claimFinalization:async()=>{calls.push('claim');return receiptRow;},markConsumed:async()=>{calls.push('consumed');},markUnknown:async()=>{calls.push('unknown');}};return {env,now:()=>1000,withStores:work=>work({reviewStore,validatorLedger,validatorReceiptStore}),resolveCurrentVersion:async()=>{calls.push('version');return 'test-version';},inspectWorkitem:async()=>{calls.push('inspect');return {state,workitemId,status:state==='APS_WORKITEM_SUCCEEDED'?'success':'inprogress',executionEnabled:false,approvalGranted:false};},finalizeReport:async()=>{calls.push('report');return {state:'SANDBOX_VALIDATOR_REOPEN_REPORT_REVIEW_READY',reportBytes:reopenReport,approvalGranted:false,reconciliation:'PROPOSE_CHANGESET_ONLY',checklist:[]};},calls};}
test('pending validator does not claim receipt or ingest report',async()=>{const h=harness('APS_WORKITEM_PENDING'),result=await finalizeGovernedSandboxValidator(h);assert.equal(result.reconciliation,'NONE');assert.deepEqual(h.calls,['version','evidenceLookup','validatorLookup','inspect']);});
test('successful validator downloads report, stores native evidence and consumes receipt',async()=>{const h=harness(),result=await finalizeGovernedSandboxValidator(h);assert.equal(result.state,'NATIVE_REOPEN_REQUIRES_ARCHON_REVIEW');assert.equal(result.approvalGranted,false);assert.deepEqual(h.calls,['version','evidenceLookup','validatorLookup','inspect','claim','report','nativeEvidence','consumed']);});
test('report ambiguity marks validator receipt unknown and never grants approval',async()=>{const h=harness();h.finalizeReport=async()=>{h.calls.push('report');throw Error('private-report-url');};await assert.rejects(finalizeGovernedSandboxValidator(h),/SANDBOX_VALIDATOR_FINALIZATION_UNKNOWN/);assert.deepEqual(h.calls,['version','evidenceLookup','validatorLookup','inspect','claim','report','unknown']);});
test('validator finalization remains disabled before database and APS',async()=>{const h=harness();h.env.ARCHON_SANDBOX_VALIDATOR_FINALIZATION_ENABLED='false';await assert.rejects(finalizeGovernedSandboxValidator(h),/FINALIZATION_DISABLED/);assert.deepEqual(h.calls,[]);});
